org.gnome.desktop.input-sources:
  xkb-options: '[''caps:ctrl_modifier'']'
org.gnome.desktop.interface:
  cursor-theme: '''Colloid-cursors'''
  document-font-name: '''Roboto 11'''
  font-name: '''Roboto 11'''
  monospace-font-name: '''FiraCode Nerd Font Mono 10'''
  show-battery-percentage: "true"
org.gnome.desktop.peripherals.touchpad:
  tap-to-click: "true"
org.gnome.desktop.privacy:
  old-files-age: uint32 7
  recent-files-max-age: "30"
  remove-old-temp-files: "true"
  remove-old-trash-files: "true"
org.gnome.desktop.search-providers:
  enabled: '[''org.gnome.Weather.desktop'', ''org.gnome.Characters.desktop'']'
org.gnome.desktop.wm.keybindings:
  maximize-vertically: '@as []'
  minimize: '@as []'
org.gnome.desktop.wm.preferences:
  titlebar-font: '''Roboto Bold 11'''
org.gnome.login-screen:
  disable-user-list: "true"
org.gnome.settings-daemon.plugins.color:
  night-light-enabled: "true"
org.gnome.settings-daemon.plugins.media-keys:
  custom-keybindings: '[''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/'', ''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/'', ''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/'', ''/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/'']'
  screensaver: '[''<Shift><Control><Alt>l'']'
? org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
: binding: '''<Control><Alt>b'''
  command: '''flatpak run com.raggesilver.BlackBox'''
  name: '''blackbox'''
? org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
: binding: '''<Control><Alt>t'''
  command: '''gnome-terminal'''
  name: '''gnome-terminal'''
? org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/
: binding: '''<Control><Alt>w'''
  command: '''flatpak run org.wezfurlong.wezterm'''
  name: '''wez'''
org.gnome.settings-daemon.plugins.power:
  sleep-inactive-ac-type: '''nothing'''
org.gnome.shell:
  favorite-apps: '[''firefox.desktop'', ''vivaldi-stable.desktop'', ''1password.desktop'', ''org.gnome.Software.desktop'', ''org.flameshot.Flameshot.desktop'', ''org.gnome.Nautilus.desktop'', ''org.wezfurlong.wezterm.desktop'']'
org.gnome.shell.extensions.nightthemeswitcher.gtk-variants:
  day: '''Catppuccin-Frappe-Standard-Flamingo-dark'''
  enabled: "true"
  night: '''Catppuccin-Mocha-Standard-Flamingo-dark'''
org.gnome.shell.extensions.nightthemeswitcher.shell-variants:
  day: '''Catppuccin-Frappe-Standard-Flamingo-dark'''
  enabled: "true"
  night: '''Catppuccin-Mocha-Standard-Flamingo-dark'''
org.gnome.shell.extensions.nightthemeswitcher.time:
  sunrise: "0.0"
  sunset: "0.016666666666666666"
org.gnome.shell.extensions.paperwm:
  use-default-background: "true"
  winprops: '[''{"wm_class":"zoom","title":"zoom","scratch_layer":true}'', ''{"wm_class":"gnome-calculator","title":"calc","scratch_layer":true}'']'
org.gnome.shell.extensions.paperwm.keybindings:
  barf-out: '[''<Super>o'']'
  center-horizontally: '[''<Super>c'']'
  close-window: '[''<Super>BackSpace'']'
  cycle-height: '[''<Super><Shift>r'']'
  cycle-width: '[''<Super>r'']'
  live-alt-tab: '[''<Super>Tab'']'
  live-alt-tab-backward: '[''<Super><Shift>Tab'']'
  move-down: '[''<Super><Ctrl>Down'']'
  move-down-workspace: '[''<Super><Ctrl>Page_Down'']'
  move-left: '[''<Control><Super>comma'', ''<Shift><Super>comma'', ''<Control><Super>Left'', ''<Control><Super>h'']'
  move-monitor-above: '[''<Shift><Control><Super>Up'', ''<Shift><Control><Super>k'']'
  move-monitor-below: '[''<Shift><Control><Super>Down'', ''<Shift><Control><Super>j'']'
  move-monitor-left: '[''<Shift><Control><Super>Left'', ''<Shift><Control><Super>h'']'
  move-monitor-right: '[''<Shift><Control><Super>Right'', ''<Shift><Control><Super>l'']'
  move-previous-workspace: '[''<Super><Ctrl>Above_Tab'']'
  move-previous-workspace-backward: '[''<Super><Shift><Ctrl>Above_Tab'']'
  move-right: '[''<Control><Super>period'', ''<Shift><Super>period'', ''<Control><Super>Right'', ''<Control><Super>l'']'
  move-up: '[''<Super><Ctrl>Up'']'
  move-up-workspace: '[''<Super><Ctrl>Page_Up'']'
  new-window: '[''<Super>Return'', ''<Super>n'']'
  paper-toggle-fullscreen: '[''<Super><shift>f'']'
  previous-workspace: '[''<Super>semicolon'']'
  previous-workspace-backward: '[''<Super><Shift>Above_Tab'']'
  resize-h-dec: '[''<Super><Shift>minus'']'
  resize-h-inc: '[''<Super><Shift>plus'']'
  resize-w-dec: '[''<Super>minus'']'
  resize-w-inc: '[''<Super>plus'']'
  slurp-in: '[''<Super>i'']'
  switch-down: '[''<Super>Down'', ''<Super>j'']'
  switch-down-workspace: '[''<Super>Page_Down'']'
  switch-first: '[''<Super>Home'', ''<Super>1'']'
  switch-focus-mode: '[''<Super><Shift>c'']'
  switch-last: '[''<Super>End'', ''<Super>0'']'
  switch-left: '[''<Super>h'', ''<Super>Left'']'
  switch-monitor-above: '[''<Shift><Super>k'', ''<Shift><Super>Up'']'
  switch-monitor-below: '[''<Shift><Super>j'', ''<Shift><Super>Down'']'
  switch-monitor-left: '[''<Shift><Super>h'', ''<Shift><Super>Left'']'
  switch-monitor-right: '[''<Shift><Super>l'', ''<Shift><Super>Right'']'
  switch-next: '[''<Super>period'']'
  switch-previous: '[''<Super>comma'']'
  switch-right: '[''<Super>l'', ''<Super>Right'']'
  switch-up: '[''<Super>Up'', ''<Super>k'']'
  switch-up-workspace: '[''<Super>Page_Up'']'
  take-window: '[''<Super>t'']'
  toggle-maximize-width: '[''<Super>f'']'
  toggle-scratch: '[''<Super><Ctrl>Escape'']'
  toggle-scratch-layer: '[''<Super><Shift>Escape'']'
  toggle-scratch-window: '[''<Super>Escape'']'
org.gtk.gtk4.Settings.FileChooser:
  sort-directories-first: "true"
