#:schema https://mise.jdx.dev/schema/mise.json

[settings]
experimental = true
lockfile = true
# locked = true
## cannot enforce until all used backends support lock
## https://mise.jdx.dev/dev-tools/mise-lock.html#backend-support

# Optional “paranoid” hardening + signature verification
paranoid = true   # extra-secure behavior (hooks/tasks etc.) :contentReference[oaicite:8]{index=8}
gpg_verify = true # verify signatures for supported tools :contentReference[oaicite:9]{index=9}

[settings.aqua]
baked_registry = true
cosign = true
minisign = true
slsa = true

[settings.npm]
package_manager = "bun"

[tools]

bun = "1.3.9"
go = "1.26.0"
node = "24.13.1"
rust = "1.93.1"

"aqua:mfontanini/presenterm" = "0.16.1"
"aqua:int128/ghcp" = "1.15.2"
"npm:@google/gemini-cli" = "0.29.5"
"npm:@fission-ai/openspec" = "1.1.1"
"npm:opkg" = "0.8.5"
"npm:ccusage" = "18.0.5"

# linters, etc
"npm:@commitlint/cli" = "20.4.2"
"npm:@fsouza/prettierd" = "0.27.0"
"npm:alex" = "11.0.1"
"npm:bash-language-server" = "5.6.0"
"npm:cspell" = "9.6.4"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:jsonlint" = "1.6.3"
"npm:markdown-toc" = "1.2.0"
"npm:markdownlint-cli" = "0.47.0"
"npm:prettier" = "3.8.1"
"npm:pyright" = "1.1.408"
"npm:sql-formatter" = "15.7.2"
"npm:sql-language-server" = "1.7.1"
"npm:stylelint" = "17.3.0"
"npm:textlint" = "15.5.1"
"pipx:ansible-lint" = "26.1.1"
"pipx:beautysh" = "6.4.2"
"pipx:gitlint-core" = "0.19.1"
"pipx:isort" = "8.0.0"
"pipx:mypy" = "1.19.1"
"pipx:pyproject-flake8" = "7.0.0"
"pipx:ruff-lsp" = "0.0.62"
"pipx:semgrep" = "1.152.0"
"pipx:sqlfluff" = "4.0.4"
"pipx:yamllint" = "1.38.0"
